version: '2'

services:

# cache redis server
 redis:
  container_name: redis
  image: redis
  restart: always
  ports:
  - 6379:6379

# sample database
 db:
  container_name: db
  image: mariadb
  restart: always
  ports:
    - 3306:3306
  volumes:
    - ./example_db.sql:/docker-entrypoint-initdb.d/dump.sql
  environment:
   MYSQL_RANDOM_ROOT_PASSWORD: "true"
   MYSQL_DATABASE: "rester-sql"
   MYSQL_USER: "rester-sql"
   MYSQL_PASSWORD: "rester-sql"

 rester-sql:
  container_name: rester-sql
  image: kevinpark/nginx-php-redis
  restart: always
  links:
    - redis:cache.rester.kr
    - db:db.rester.kr
  volumes:
   - ./default.conf:/etc/nginx/sites-available/default.conf:ro
   - ./src:/var/www/html
   - ./cfg:/var/www/cfg:ro
  ports:
  - '80:80'
